###
POST http://localhost:3000/signup
Content-Type: application/json

{
    "name" : "San",
    "id" : "3",
    "password" : "password123",
    "role":"user"
}

###

####
POST http://localhost:3000/login
Content-Type: application/json

{
    "name" : "Anto",
    "password" : "password123"
    //"role" : "admin"

}

####

POST http://localhost:3000/token
Content-Type: application/json

{
    "token":"$2b$10$mAaLqZYY/LQ1MRSji6sU/.x.7c.svuCtrFpQ9Eyqy9Iwt/6qKbI4K"
}


###


GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQW50byIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzc0NDQ0MzE3LCJleHAiOjE3NzQ0NDQzNzd9.9IrAll-ufTDRWHdFmnf4mz4awq3rJhOC2PPV1Tbo4OI


###
GET http://localhost:3000/user/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQW50byIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzc0NDQ0MzE3LCJleHAiOjE3NzQ0NDQzNzd9.9IrAll-ufTDRWHdFmnf4mz4awq3rJhOC2PPV1Tbo4OI

###
DELETE  http://localhost:3000/user/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQW50byIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzc0NDQ0MzE3LCJleHAiOjE3NzQ0NDQzNzd9.9IrAll-ufTDRWHdFmnf4mz4awq3rJhOC2PPV1Tbo4OI
Content-Type: application/json


###

DELETE  http://localhost:3000/logout
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2FuIiwiaWF0IjoxNzczNzQwNTIzfQ.jUYDEGLLhYrmbXYEvyqw10DRzfCI5gRYNNWCODrGclg"
}