POST http://localhost:3000/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicm9ja3kiLCJpYXQiOjE3NzM2NTY1NDd9.Gf1eapxmVYirvmvRYiyZkhY1TKgQUktOyknAoknVHQQ"
}



####
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "name" : "rocky",
    "password" : "password123"

}

###


GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicm9ja3kiLCJpYXQiOjE3NzM2NTYyNzUsImV4cCI6MTc3MzY1NjMzNX0.Jjs8AzkeujPAaOePQO14H4bVV6sAEwE3Tk9j_LIwPL8

###
GET http://localhost:3000/user/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicm9ja3kiLCJpYXQiOjE3NzM2NDU1OTUsImV4cCI6MTc3MzY0NTY1NX0.QYdD3-gTv20lZcrqvvApNNfd8bMhg75jWx-wUPmvULE



###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name" : "Anto",
    "id" : "2",
    "password" : "password123"
}

###
DELETE  http://localhost:3000/user/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicm9ja3kiLCJpYXQiOjE3NzMzMjMwNTN9.6K-YUZ0NaIbA1gDkYrsMI3Y3l3yDvBt60y4-sMVkb_A
Content-Type: application/json

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "name" : "rocky"
}

###

DELETE  http://localhost:3000/logout
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicm9ja3kiLCJpYXQiOjE3NzM2NTMxMjN9.N6C7NCnI-qs_HtbW60YRs_opxm-t0zECkBYaY-tbOa8"
}